name: Update Proxy List

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次

jobs:
  update-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download proxy list
        run: |
          curl -o proxy.txt "https://fineproxy.org/wp-admin/admin-ajax.php?action=proxylister_download&nonce=a6998eed3f&format=txt&filter=%7B%7D"

      - name: Commit and push changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add proxy.txt
          git commit -m "Update proxy list" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
